#!/usr/bin/env bash

if [ ! -n "$VIRTUAL_ENV" ]; then
        echo "VENV is not active"
        echo "Activating VENV"
        source venv/bin/activate
fi

echo "Installing required packages"
pip install -r requirements.txt

echo "Starting the app"
uvicorn main:app --reload
